language: rust
rust:
  - stable
  - nightly
matrix:
  allow_failures:
    - rust: nightly

before_install:
  - sudo add-apt-repository --yes ppa:codegear/release
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq --force-yes premake4
  - sudo apt-get install xorg-dev libglu1-mesa-dev
script:
  # glfw
  # - git clone https://github.com/glfw/glfw.git
  # - cd glfw
  # - git checkout 3.0.3
  # - cmake -DBUILD_SHARED_LIBS=ON .
  # - make
  # - sudo make install
  # - cd ..

  - cargo build --features "gl3"
