before_install:
  - sudo add-apt-repository --yes ppa:hansjorg/rust
  - sudo add-apt-repository --yes ppa:cmrx64/cargo
  - sudo add-apt-repository --yes ppa:codegear/release
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq rust-nightly cargo
  - sudo apt-get install -qq premake4
  - sudo apt-get install libXxf86vm-dev
script:
  - mkdir deps
  - cd deps
  # Install glfw lib
  - git clone --depth=1 https://github.com/glfw/glfw.git
  - cd glfw
  - cmake -DBUILD_SHARED_LIBS=ON
  - make glfw # build only .so files
  - sudo make install
  #- cp src/libglfw.so* .. # copy dynamic libraries
  - cd ..
  - cargo build
