[package]
name = "nanovg"
version = "0.1.0"
authors = ["Kevin Kelley <kevin@kelleysoft.com>"]

[[lib]]
name = "nanovg"

[[bin]]
name = "example_gl3"
path = "examples/example_gl3.rs"

[dependencies.glfw]
git = "https://github.com/bjz/glfw-rs"

[dependencies.gl]
git = "https://github.com/bjz/gl-rs"
