[package]
name = "nanovg"
version = "0.2.0"
authors = ["Kevin Kelley <kevin@kelleysoft.com>"]
build = "build.rs"

[lib]
name = "nanovg"

[features]
gl2 = []
gl3 = []
gles2 = []
gles3 = []

[dependencies]
libc = "*"
bitflags = "0.1"

[build-dependencies]
gcc = "*"
